version: "2.2"

services:
  web-reg:
    build: web/
    restart: always
    ports:
      - "80:80"
    cpus: 0.5
    mem_limit: 1024m
    environment:
      - MYSQL_HOST=mysqli
      - MYSQL_USER=ctf
      - MYSQL_PASSWORD=bchjhadbsabdjbahsnxmcsdjh
      - MYSQL_DATABASE=challenge
    depends_on:
      - mysqli

  mysqli:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    cpus: 0.5
    mem_limit: 2048m
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=ctf
      - MYSQL_PASSWORD=bchjhadbsabdjbahsnxmcsdjh
      - MYSQL_DATABASE=challenge
    volumes:
      - "./mysql/:/docker-entrypoint-initdb.d/"